# Generated by Django 4.2.7 on 2025-04-18 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bot_id', models.CharField(max_length=50, unique=True)),
                ('bot_token', models.CharField(max_length=100)),
                ('bot_username', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VPNServer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('server_name', models.CharField(max_length=100)),
                ('server_location', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('cert_sha', models.CharField(max_length=255)),
                ('api_url', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='vpn_service.city')),
            ],
        ),
        migrations.CreateModel(
            name='VPNKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('outline_id', models.CharField(max_length=50)),
                ('access_url', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('traffic_limit', models.BigIntegerField(default=0)),
                ('traffic_used', models.BigIntegerField(default=0)),
                ('traffic_last_period_bytes', models.BigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_keys', to='vpn_service.user')),
                ('vpn_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_keys', to='vpn_service.vpnserver')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='vpn_service.country'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('city_name', 'country')},
        ),
    ]
