# Generated by Django 4.2.7 on 2025-04-17 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.IntegerField()),
                ('traffic_limit_gb', models.IntegerField()),
                ('max_devices', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VPNServer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('server_name', models.CharField(max_length=100, unique=True)),
                ('server_ip', models.GenericIPAddressField(unique=True)),
                ('api_key', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('server_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_servers', to='vpn.city')),
            ],
        ),
        migrations.CreateModel(
            name='VPNService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('protocol', models.CharField(choices=[('wireguard', 'WireGuard'), ('openvpn', 'OpenVPN'), ('ikev2', 'IKEv2')], default='wireguard', max_length=50)),
                ('port', models.IntegerField(default=51820)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='vpn.vpnserver')),
            ],
            options={
                'unique_together': {('server', 'protocol', 'port')},
            },
        ),
        migrations.CreateModel(
            name='VPNKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vpn_key', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('traffic_last_period_bytes', models.BigIntegerField(default=0)),
                ('traffic_limit', models.BigIntegerField(default=0)),
                ('is_traffic_limit_exceeded', models.BooleanField(default=False)),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpn_keys', to='vpn.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_keys', to='vpn.user')),
                ('vpn_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_keys', to='vpn.vpnserver')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bot_token', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='vpn.vpnservice')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='vpn.country'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('city_name', 'country')},
        ),
    ]
